# This is a basic workflow to help you get started with Actions

name: Hello World
# Controls when the workflow will run
on: push
jobs: 
  # This workflow contains a single job called "build"
  hello-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Echo text
        run: echo "Hello, world!"

